export const  estados = [
  { sigla: 'Acre', nome: 'Acre' },
  { sigla: 'Alagoas', nome: 'Alagoas' },
  { sigla: 'Amapá', nome: 'Amapá' },
  { sigla: 'Amazonas', nome: 'Amazonas' },
  { sigla: 'Bahia', nome: 'Bahia' },
  { sigla: 'Ceará', nome: 'Ceará' },
  { sigla: 'Distrito Federal', nome: 'Distrito Federal' },
  { sigla: 'Espírito Santo', nome: 'Espírito Santo' },
  { sigla: 'Goiás', nome: 'Goiás' },
  { sigla: 'Maranhão', nome: 'Maranhão' },
  { sigla: 'Mato Grosso', nome: 'Mato Grosso' },
  { sigla: 'Mato Grosso do Sul', nome: 'Mato Grosso do Sul' },
  { sigla: 'Minas Gerais', nome: 'Minas Gerais' },
  { sigla: 'Pará', nome: 'Pará' },
  { sigla: 'Paraíba', nome: 'Paraíba' },
  { sigla: 'Paraná', nome: 'Paraná' },
  { sigla: 'Pernambuco', nome: 'Pernambuco' },
  { sigla: 'Piauí', nome: 'Piauí' },
  { sigla: 'Rio de Janeiro', nome: 'Rio de Janeiro' },
  { sigla: 'Rio Grande do Norte', nome: 'Rio Grande do Norte' },
  { sigla: 'Rio Grande do Sul', nome: 'Rio Grande do Sul' },
  { sigla: 'Rondônia', nome: 'Rondônia' },
  { sigla: 'Roraima', nome: 'Roraima' },
  { sigla: 'Santa Catarina', nome: 'Santa Catarina' },
  { sigla: 'São Paulo', nome: 'São Paulo' },
  { sigla: 'Sergipe', nome: 'Sergipe' },
  { sigla: 'Tocantins', nome: 'Tocantins' }
];
